function NavBar() {
    return (
        <nav className={"navbar"}>
            <ul className={"navbar-nav"}>
                <li className={"nav-item"}><a className={"nav-link"} href={"#"}>Home</a></li>
                <li className={"nav-item"}><a className={"nav-link"} href={"#"}>About</a></li>
                <li className={"nav-item"}><a className={"nav-link"} href={"#"}>Projects</a></li>
                <li className={"nav-item"}><a className={"nav-link"} href={"#"}>Skills</a></li>
                <li className={"nav-item"}><a className={"nav-link"} href={"#"}>Contact</a></li>
            </ul>
        </nav>
    );
}

export const FrontPage = () => {
    return(
        <>
            <NavBar/>
            <div className={"main-head"}>
                <h2>Gabriel Øgård</h2>
                <p className={"line-1 anim-typewriter"}>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ipsum suspendisse ultrices gravida dictum fusce. Volutpat est velit egestas dui id ornare arcu odio ut. Odio ut sem nulla pharetra. Rutrum quisque non tellus orci ac auctor augue mauris. Commodo odio aenean sed adipiscing diam donec. Risus nullam eget felis eget nunc lobortis mattis. Euismod nisi porta lorem mollis aliquam ut porttitor leo. Commodo quis imperdiet massa tincidunt. Consequat id porta nibh venenatis cras sed felis. Interdum varius sit amet mattis vulputate enim. Gravida quis blandit turpis cursus in hac. Sollicitudin aliquam ultrices sagittis orci a scelerisque. Ultrices neque ornare aenean euismod elementum nisi quis. Malesuada fames ac turpis egestas integer. Lectus magna fringilla urna porttitor rhoncus dolor.

                    Augue mauris augue neque gravida in fermentum et sollicitudin ac. Semper auctor neque vitae tempus quam pellentesque nec. Feugiat nibh sed pulvinar proin gravida hendrerit lectus. Suspendisse ultrices gravida dictum fusce ut placerat. Dictum at tempor commodo ullamcorper. Consectetur lorem donec massa sapien faucibus et molestie ac feugiat. Quis enim lobortis scelerisque fermentum dui faucibus in. Felis imperdiet proin fermentum leo vel. Purus non enim praesent elementum facilisis leo vel fringilla. Felis imperdiet proin fermentum leo vel. Posuere sollicitudin aliquam ultrices sagittis orci. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Tempor commodo ullamcorper a lacus vestibulum sed arcu non odio. Arcu risus quis varius quam quisque id diam vel. In nibh mauris cursus mattis molestie. Pharetra et ultrices neque ornare aenean.

                    Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula. Urna porttitor rhoncus dolor purus non enim praesent elementum. Venenatis tellus in metus vulputate eu scelerisque felis. At ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget. Integer quis auctor elit sed vulputate mi. Ut consequat semper viverra nam libero justo laoreet sit amet. Et tortor at risus viverra adipiscing at. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam. Molestie at elementum eu facilisis sed odio morbi. Congue eu consequat ac felis donec et odio. Volutpat diam ut venenatis tellus in metus vulputate eu scelerisque. Diam vulputate ut pharetra sit amet aliquam. Ultrices vitae auctor eu augue ut lectus arcu bibendum at. A diam maecenas sed enim ut sem viverra aliquet eget. Enim nunc faucibus a pellentesque sit amet porttitor.

                    Bibendum neque egestas congue quisque egestas diam in. Ut sem viverra aliquet eget. Consectetur a erat nam at lectus urna. Pharetra massa massa ultricies mi quis hendrerit dolor. Vel elit scelerisque mauris pellentesque pulvinar. Sagittis vitae et leo duis ut diam. Non curabitur gravida arcu ac tortor dignissim. Mattis enim ut tellus elementum sagittis. Nunc scelerisque viverra mauris in aliquam sem. At urna condimentum mattis pellentesque. Vitae turpis massa sed elementum tempus egestas. Neque ornare aenean euismod elementum nisi. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan.

                    Lacus vestibulum sed arcu non odio euismod. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Libero justo laoreet sit amet cursus sit amet. Risus feugiat in ante metus dictum at tempor. Sit amet nisl suscipit adipiscing. Dui sapien eget mi proin sed libero enim sed. Arcu bibendum at varius vel. Viverra ipsum nunc aliquet bibendum enim facilisis. Ac turpis egestas integer eget. Odio ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. Urna cursus eget nunc scelerisque viverra mauris. Mi eget mauris pharetra et ultrices neque ornare aenean.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ipsum suspendisse ultrices gravida dictum fusce. Volutpat est velit egestas dui id ornare arcu odio ut. Odio ut sem nulla pharetra. Rutrum quisque non tellus orci ac auctor augue mauris. Commodo odio aenean sed adipiscing diam donec. Risus nullam eget felis eget nunc lobortis mattis. Euismod nisi porta lorem mollis aliquam ut porttitor leo. Commodo quis imperdiet massa tincidunt. Consequat id porta nibh venenatis cras sed felis. Interdum varius sit amet mattis vulputate enim. Gravida quis blandit turpis cursus in hac. Sollicitudin aliquam ultrices sagittis orci a scelerisque. Ultrices neque ornare aenean euismod elementum nisi quis. Malesuada fames ac turpis egestas integer. Lectus magna fringilla urna porttitor rhoncus dolor.

                    Augue mauris augue neque gravida in fermentum et sollicitudin ac. Semper auctor neque vitae tempus quam pellentesque nec. Feugiat nibh sed pulvinar proin gravida hendrerit lectus. Suspendisse ultrices gravida dictum fusce ut placerat. Dictum at tempor commodo ullamcorper. Consectetur lorem donec massa sapien faucibus et molestie ac feugiat. Quis enim lobortis scelerisque fermentum dui faucibus in. Felis imperdiet proin fermentum leo vel. Purus non enim praesent elementum facilisis leo vel fringilla. Felis imperdiet proin fermentum leo vel. Posuere sollicitudin aliquam ultrices sagittis orci. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Tempor commodo ullamcorper a lacus vestibulum sed arcu non odio. Arcu risus quis varius quam quisque id diam vel. In nibh mauris cursus mattis molestie. Pharetra et ultrices neque ornare aenean.

                    Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula. Urna porttitor rhoncus dolor purus non enim praesent elementum. Venenatis tellus in metus vulputate eu scelerisque felis. At ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget. Integer quis auctor elit sed vulputate mi. Ut consequat semper viverra nam libero justo laoreet sit amet. Et tortor at risus viverra adipiscing at. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam. Molestie at elementum eu facilisis sed odio morbi. Congue eu consequat ac felis donec et odio. Volutpat diam ut venenatis tellus in metus vulputate eu scelerisque. Diam vulputate ut pharetra sit amet aliquam. Ultrices vitae auctor eu augue ut lectus arcu bibendum at. A diam maecenas sed enim ut sem viverra aliquet eget. Enim nunc faucibus a pellentesque sit amet porttitor.

                    Bibendum neque egestas congue quisque egestas diam in. Ut sem viverra aliquet eget. Consectetur a erat nam at lectus urna. Pharetra massa massa ultricies mi quis hendrerit dolor. Vel elit scelerisque mauris pellentesque pulvinar. Sagittis vitae et leo duis ut diam. Non curabitur gravida arcu ac tortor dignissim. Mattis enim ut tellus elementum sagittis. Nunc scelerisque viverra mauris in aliquam sem. At urna condimentum mattis pellentesque. Vitae turpis massa sed elementum tempus egestas. Neque ornare aenean euismod elementum nisi. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan.

                    Lacus vestibulum sed arcu non odio euismod. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Libero justo laoreet sit amet cursus sit amet. Risus feugiat in ante metus dictum at tempor. Sit amet nisl suscipit adipiscing. Dui sapien eget mi proin sed libero enim sed. Arcu bibendum at varius vel. Viverra ipsum nunc aliquet bibendum enim facilisis. Ac turpis egestas integer eget. Odio ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. Urna cursus eget nunc scelerisque viverra mauris. Mi eget mauris pharetra et ultrices neque ornare aenean.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ipsum suspendisse ultrices gravida dictum fusce. Volutpat est velit egestas dui id ornare arcu odio ut. Odio ut sem nulla pharetra. Rutrum quisque non tellus orci ac auctor augue mauris. Commodo odio aenean sed adipiscing diam donec. Risus nullam eget felis eget nunc lobortis mattis. Euismod nisi porta lorem mollis aliquam ut porttitor leo. Commodo quis imperdiet massa tincidunt. Consequat id porta nibh venenatis cras sed felis. Interdum varius sit amet mattis vulputate enim. Gravida quis blandit turpis cursus in hac. Sollicitudin aliquam ultrices sagittis orci a scelerisque. Ultrices neque ornare aenean euismod elementum nisi quis. Malesuada fames ac turpis egestas integer. Lectus magna fringilla urna porttitor rhoncus dolor.

                    Augue mauris augue neque gravida in fermentum et sollicitudin ac. Semper auctor neque vitae tempus quam pellentesque nec. Feugiat nibh sed pulvinar proin gravida hendrerit lectus. Suspendisse ultrices gravida dictum fusce ut placerat. Dictum at tempor commodo ullamcorper. Consectetur lorem donec massa sapien faucibus et molestie ac feugiat. Quis enim lobortis scelerisque fermentum dui faucibus in. Felis imperdiet proin fermentum leo vel. Purus non enim praesent elementum facilisis leo vel fringilla. Felis imperdiet proin fermentum leo vel. Posuere sollicitudin aliquam ultrices sagittis orci. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Tempor commodo ullamcorper a lacus vestibulum sed arcu non odio. Arcu risus quis varius quam quisque id diam vel. In nibh mauris cursus mattis molestie. Pharetra et ultrices neque ornare aenean.

                    Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula. Urna porttitor rhoncus dolor purus non enim praesent elementum. Venenatis tellus in metus vulputate eu scelerisque felis. At ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget. Integer quis auctor elit sed vulputate mi. Ut consequat semper viverra nam libero justo laoreet sit amet. Et tortor at risus viverra adipiscing at. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam. Molestie at elementum eu facilisis sed odio morbi. Congue eu consequat ac felis donec et odio. Volutpat diam ut venenatis tellus in metus vulputate eu scelerisque. Diam vulputate ut pharetra sit amet aliquam. Ultrices vitae auctor eu augue ut lectus arcu bibendum at. A diam maecenas sed enim ut sem viverra aliquet eget. Enim nunc faucibus a pellentesque sit amet porttitor.

                    Bibendum neque egestas congue quisque egestas diam in. Ut sem viverra aliquet eget. Consectetur a erat nam at lectus urna. Pharetra massa massa ultricies mi quis hendrerit dolor. Vel elit scelerisque mauris pellentesque pulvinar. Sagittis vitae et leo duis ut diam. Non curabitur gravida arcu ac tortor dignissim. Mattis enim ut tellus elementum sagittis. Nunc scelerisque viverra mauris in aliquam sem. At urna condimentum mattis pellentesque. Vitae turpis massa sed elementum tempus egestas. Neque ornare aenean euismod elementum nisi. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan.

                    Lacus vestibulum sed arcu non odio euismod. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Libero justo laoreet sit amet cursus sit amet. Risus feugiat in ante metus dictum at tempor. Sit amet nisl suscipit adipiscing. Dui sapien eget mi proin sed libero enim sed. Arcu bibendum at varius vel. Viverra ipsum nunc aliquet bibendum enim facilisis. Ac turpis egestas integer eget. Odio ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. Urna cursus eget nunc scelerisque viverra mauris. Mi eget mauris pharetra et ultrices neque ornare aenean.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ipsum suspendisse ultrices gravida dictum fusce. Volutpat est velit egestas dui id ornare arcu odio ut. Odio ut sem nulla pharetra. Rutrum quisque non tellus orci ac auctor augue mauris. Commodo odio aenean sed adipiscing diam donec. Risus nullam eget felis eget nunc lobortis mattis. Euismod nisi porta lorem mollis aliquam ut porttitor leo. Commodo quis imperdiet massa tincidunt. Consequat id porta nibh venenatis cras sed felis. Interdum varius sit amet mattis vulputate enim. Gravida quis blandit turpis cursus in hac. Sollicitudin aliquam ultrices sagittis orci a scelerisque. Ultrices neque ornare aenean euismod elementum nisi quis. Malesuada fames ac turpis egestas integer. Lectus magna fringilla urna porttitor rhoncus dolor.

                    Augue mauris augue neque gravida in fermentum et sollicitudin ac. Semper auctor neque vitae tempus quam pellentesque nec. Feugiat nibh sed pulvinar proin gravida hendrerit lectus. Suspendisse ultrices gravida dictum fusce ut placerat. Dictum at tempor commodo ullamcorper. Consectetur lorem donec massa sapien faucibus et molestie ac feugiat. Quis enim lobortis scelerisque fermentum dui faucibus in. Felis imperdiet proin fermentum leo vel. Purus non enim praesent elementum facilisis leo vel fringilla. Felis imperdiet proin fermentum leo vel. Posuere sollicitudin aliquam ultrices sagittis orci. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Tempor commodo ullamcorper a lacus vestibulum sed arcu non odio. Arcu risus quis varius quam quisque id diam vel. In nibh mauris cursus mattis molestie. Pharetra et ultrices neque ornare aenean.

                    Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula. Urna porttitor rhoncus dolor purus non enim praesent elementum. Venenatis tellus in metus vulputate eu scelerisque felis. At ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget. Integer quis auctor elit sed vulputate mi. Ut consequat semper viverra nam libero justo laoreet sit amet. Et tortor at risus viverra adipiscing at. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam. Molestie at elementum eu facilisis sed odio morbi. Congue eu consequat ac felis donec et odio. Volutpat diam ut venenatis tellus in metus vulputate eu scelerisque. Diam vulputate ut pharetra sit amet aliquam. Ultrices vitae auctor eu augue ut lectus arcu bibendum at. A diam maecenas sed enim ut sem viverra aliquet eget. Enim nunc faucibus a pellentesque sit amet porttitor.

                    Bibendum neque egestas congue quisque egestas diam in. Ut sem viverra aliquet eget. Consectetur a erat nam at lectus urna. Pharetra massa massa ultricies mi quis hendrerit dolor. Vel elit scelerisque mauris pellentesque pulvinar. Sagittis vitae et leo duis ut diam. Non curabitur gravida arcu ac tortor dignissim. Mattis enim ut tellus elementum sagittis. Nunc scelerisque viverra mauris in aliquam sem. At urna condimentum mattis pellentesque. Vitae turpis massa sed elementum tempus egestas. Neque ornare aenean euismod elementum nisi. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan.

                    Lacus vestibulum sed arcu non odio euismod. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Libero justo laoreet sit amet cursus sit amet. Risus feugiat in ante metus dictum at tempor. Sit amet nisl suscipit adipiscing. Dui sapien eget mi proin sed libero enim sed. Arcu bibendum at varius vel. Viverra ipsum nunc aliquet bibendum enim facilisis. Ac turpis egestas integer eget. Odio ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. Urna cursus eget nunc scelerisque viverra mauris. Mi eget mauris pharetra et ultrices neque ornare aenean.
                    Lacus vestibulum sed arcu non odio euismod. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Libero justo laoreet sit amet cursus sit amet. Risus feugiat in ante metus dictum at tempor. Sit amet nisl suscipit adipiscing. Dui sapien eget mi proin sed libero enim sed. Arcu bibendum at varius vel. Viverra ipsum nunc aliquet bibendum enim facilisis. Ac turpis egestas integer eget. Odio ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. Urna cursus eget nunc scelerisque viverra mauris. Mi eget mauris pharetra et ultrices neque ornare aenean.
                </p>
            </div>
        </>
    );
}